name: Build package

on:
  push:
    tags: ['v*']

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  createPackage:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create package
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        chmod +x ./tools/mo
        bash ./tools/create_package.sh "${{github.ref_name}}" ./output

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: ./output/*
